(cl:defpackage tutorial7-msg
  (:use )
  (:export
   "<BLINKACTION>"
   "BLINKACTION"
   "<BLINKACTIONFEEDBACK>"
   "BLINKACTIONFEEDBACK"
   "<BLINKACTIONGOAL>"
   "BLINKACTIONGOAL"
   "<BLINKACTIONRESULT>"
   "BLINKACTIONRESULT"
   "<BLINKFEEDBACK>"
   "BLINKFEEDBACK"
   "<BLINKGOAL>"
   "BLINKGOAL"
   "<BLINKRESULT>"
   "BLINKRESULT"
  ))

