; Auto-generated. Do not edit!


(cl:in-package tutorial7-msg)


;//! \htmlinclude blinkActionGoal.msg.html

(cl:defclass <blinkActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type tutorial7-msg:blinkGoal
    :initform (cl:make-instance 'tutorial7-msg:blinkGoal)))
)

(cl:defclass blinkActionGoal (<blinkActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <blinkActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'blinkActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tutorial7-msg:<blinkActionGoal> is deprecated: use tutorial7-msg:blinkActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <blinkActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial7-msg:header-val is deprecated.  Use tutorial7-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <blinkActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial7-msg:goal_id-val is deprecated.  Use tutorial7-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <blinkActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial7-msg:goal-val is deprecated.  Use tutorial7-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <blinkActionGoal>) ostream)
  "Serializes a message object of type '<blinkActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <blinkActionGoal>) istream)
  "Deserializes a message object of type '<blinkActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<blinkActionGoal>)))
  "Returns string type for a message object of type '<blinkActionGoal>"
  "tutorial7/blinkActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'blinkActionGoal)))
  "Returns string type for a message object of type 'blinkActionGoal"
  "tutorial7/blinkActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<blinkActionGoal>)))
  "Returns md5sum for a message object of type '<blinkActionGoal>"
  "8fb9f71a23feed1923381dc04a3cab38")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'blinkActionGoal)))
  "Returns md5sum for a message object of type 'blinkActionGoal"
  "8fb9f71a23feed1923381dc04a3cab38")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<blinkActionGoal>)))
  "Returns full string definition for message of type '<blinkActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%blinkGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: tutorial7/blinkGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal ~%~%std_msgs/ColorRGBA[] colors  ~%std_msgs/ColorRGBA bg_color  ## background  ~%duration blink_duration~%float32 blink_rate_mean~%float32 blink_rate_sd~%~%~%================================================================================~%MSG: std_msgs/ColorRGBA~%float32 r~%float32 g~%float32 b~%float32 a~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'blinkActionGoal)))
  "Returns full string definition for message of type 'blinkActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%blinkGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: tutorial7/blinkGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal ~%~%std_msgs/ColorRGBA[] colors  ~%std_msgs/ColorRGBA bg_color  ## background  ~%duration blink_duration~%float32 blink_rate_mean~%float32 blink_rate_sd~%~%~%================================================================================~%MSG: std_msgs/ColorRGBA~%float32 r~%float32 g~%float32 b~%float32 a~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <blinkActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <blinkActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'blinkActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
