; Auto-generated. Do not edit!


(cl:in-package tutorial7-msg)


;//! \htmlinclude blinkResult.msg.html

(cl:defclass <blinkResult> (roslisp-msg-protocol:ros-message)
  ((still_blinking
    :reader still_blinking
    :initarg :still_blinking
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass blinkResult (<blinkResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <blinkResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'blinkResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tutorial7-msg:<blinkResult> is deprecated: use tutorial7-msg:blinkResult instead.")))

(cl:ensure-generic-function 'still_blinking-val :lambda-list '(m))
(cl:defmethod still_blinking-val ((m <blinkResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial7-msg:still_blinking-val is deprecated.  Use tutorial7-msg:still_blinking instead.")
  (still_blinking m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <blinkResult>) ostream)
  "Serializes a message object of type '<blinkResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'still_blinking) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <blinkResult>) istream)
  "Deserializes a message object of type '<blinkResult>"
    (cl:setf (cl:slot-value msg 'still_blinking) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<blinkResult>)))
  "Returns string type for a message object of type '<blinkResult>"
  "tutorial7/blinkResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'blinkResult)))
  "Returns string type for a message object of type 'blinkResult"
  "tutorial7/blinkResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<blinkResult>)))
  "Returns md5sum for a message object of type '<blinkResult>"
  "53e041b81450f9247036f13b3c0bf822")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'blinkResult)))
  "Returns md5sum for a message object of type 'blinkResult"
  "53e041b81450f9247036f13b3c0bf822")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<blinkResult>)))
  "Returns full string definition for message of type '<blinkResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result ~%bool still_blinking~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'blinkResult)))
  "Returns full string definition for message of type 'blinkResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result ~%bool still_blinking~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <blinkResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <blinkResult>))
  "Converts a ROS message object to a list"
  (cl:list 'blinkResult
    (cl:cons ':still_blinking (still_blinking msg))
))
