; Auto-generated. Do not edit!


(cl:in-package tutorial7-msg)


;//! \htmlinclude blinkFeedback.msg.html

(cl:defclass <blinkFeedback> (roslisp-msg-protocol:ros-message)
  ((last_color
    :reader last_color
    :initarg :last_color
    :type std_msgs-msg:ColorRGBA
    :initform (cl:make-instance 'std_msgs-msg:ColorRGBA)))
)

(cl:defclass blinkFeedback (<blinkFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <blinkFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'blinkFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tutorial7-msg:<blinkFeedback> is deprecated: use tutorial7-msg:blinkFeedback instead.")))

(cl:ensure-generic-function 'last_color-val :lambda-list '(m))
(cl:defmethod last_color-val ((m <blinkFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial7-msg:last_color-val is deprecated.  Use tutorial7-msg:last_color instead.")
  (last_color m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <blinkFeedback>) ostream)
  "Serializes a message object of type '<blinkFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'last_color) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <blinkFeedback>) istream)
  "Deserializes a message object of type '<blinkFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'last_color) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<blinkFeedback>)))
  "Returns string type for a message object of type '<blinkFeedback>"
  "tutorial7/blinkFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'blinkFeedback)))
  "Returns string type for a message object of type 'blinkFeedback"
  "tutorial7/blinkFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<blinkFeedback>)))
  "Returns md5sum for a message object of type '<blinkFeedback>"
  "6f1f94fb3eb06412264f6e0c5e72cfab")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'blinkFeedback)))
  "Returns md5sum for a message object of type 'blinkFeedback"
  "6f1f94fb3eb06412264f6e0c5e72cfab")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<blinkFeedback>)))
  "Returns full string definition for message of type '<blinkFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback ~%std_msgs/ColorRGBA last_color~%~%~%================================================================================~%MSG: std_msgs/ColorRGBA~%float32 r~%float32 g~%float32 b~%float32 a~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'blinkFeedback)))
  "Returns full string definition for message of type 'blinkFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback ~%std_msgs/ColorRGBA last_color~%~%~%================================================================================~%MSG: std_msgs/ColorRGBA~%float32 r~%float32 g~%float32 b~%float32 a~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <blinkFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'last_color))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <blinkFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'blinkFeedback
    (cl:cons ':last_color (last_color msg))
))
