(cl:in-package nao_control_tutorial_2-srv)
(cl:export '(JOINT_NAME-VAL
          JOINT_NAME
          X_POS-VAL
          X_POS
          Y_POS-VAL
          Y_POS
          Z_POS-VAL
          Z_POS
          X_ROT-VAL
          X_ROT
          Y_ROT-VAL
          Y_ROT
          Z_ROT-VAL
          Z_ROT
          MAX_VEL-VAL
          MAX_VEL
          EXE_TIME-VAL
          EXE_TIME
          X_POS-VAL
          X_POS
          Y_POS-VAL
          Y_POS
          Z_POS-VAL
          Z_POS
          X_ROT-VAL
          X_ROT
          Y_ROT-VAL
          Y_ROT
          Z_ROT-VAL
          Z_ROT
))