// Generated by gencpp from file nao_control_tutorial_2/MoveJoints.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_TUTORIAL_2_MESSAGE_MOVEJOINTS_H
#define NAO_CONTROL_TUTORIAL_2_MESSAGE_MOVEJOINTS_H

#include <ros/service_traits.h>


#include <nao_control_tutorial_2/MoveJointsRequest.h>
#include <nao_control_tutorial_2/MoveJointsResponse.h>


namespace nao_control_tutorial_2
{

struct MoveJoints
{

typedef MoveJointsRequest Request;
typedef MoveJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveJoints
} // namespace nao_control_tutorial_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_control_tutorial_2::MoveJoints > {
  static const char* value()
  {
    return "998e30efad9a2f14084aad7450a533af";
  }

  static const char* value(const ::nao_control_tutorial_2::MoveJoints&) { return value(); }
};

template<>
struct DataType< ::nao_control_tutorial_2::MoveJoints > {
  static const char* value()
  {
    return "nao_control_tutorial_2/MoveJoints";
  }

  static const char* value(const ::nao_control_tutorial_2::MoveJoints&) { return value(); }
};


// service_traits::MD5Sum< ::nao_control_tutorial_2::MoveJointsRequest> should match 
// service_traits::MD5Sum< ::nao_control_tutorial_2::MoveJoints > 
template<>
struct MD5Sum< ::nao_control_tutorial_2::MoveJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control_tutorial_2::MoveJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_2::MoveJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control_tutorial_2::MoveJointsRequest> should match 
// service_traits::DataType< ::nao_control_tutorial_2::MoveJoints > 
template<>
struct DataType< ::nao_control_tutorial_2::MoveJointsRequest>
{
  static const char* value()
  {
    return DataType< ::nao_control_tutorial_2::MoveJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_2::MoveJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_control_tutorial_2::MoveJointsResponse> should match 
// service_traits::MD5Sum< ::nao_control_tutorial_2::MoveJoints > 
template<>
struct MD5Sum< ::nao_control_tutorial_2::MoveJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control_tutorial_2::MoveJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_2::MoveJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control_tutorial_2::MoveJointsResponse> should match 
// service_traits::DataType< ::nao_control_tutorial_2::MoveJoints > 
template<>
struct DataType< ::nao_control_tutorial_2::MoveJointsResponse>
{
  static const char* value()
  {
    return DataType< ::nao_control_tutorial_2::MoveJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_2::MoveJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_CONTROL_TUTORIAL_2_MESSAGE_MOVEJOINTS_H
