// Generated by gencpp from file nao_control_tutorial_2/MoveJointsResponse.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_TUTORIAL_2_MESSAGE_MOVEJOINTSRESPONSE_H
#define NAO_CONTROL_TUTORIAL_2_MESSAGE_MOVEJOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_control_tutorial_2
{
template <class ContainerAllocator>
struct MoveJointsResponse_
{
  typedef MoveJointsResponse_<ContainerAllocator> Type;

  MoveJointsResponse_()
    : x_pos(0.0)
    , y_pos(0.0)
    , z_pos(0.0)
    , x_rot(0.0)
    , y_rot(0.0)
    , z_rot(0.0)  {
    }
  MoveJointsResponse_(const ContainerAllocator& _alloc)
    : x_pos(0.0)
    , y_pos(0.0)
    , z_pos(0.0)
    , x_rot(0.0)
    , y_rot(0.0)
    , z_rot(0.0)  {
  (void)_alloc;
    }



   typedef float _x_pos_type;
  _x_pos_type x_pos;

   typedef float _y_pos_type;
  _y_pos_type y_pos;

   typedef float _z_pos_type;
  _z_pos_type z_pos;

   typedef float _x_rot_type;
  _x_rot_type x_rot;

   typedef float _y_rot_type;
  _y_rot_type y_rot;

   typedef float _z_rot_type;
  _z_rot_type z_rot;





  typedef boost::shared_ptr< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveJointsResponse_

typedef ::nao_control_tutorial_2::MoveJointsResponse_<std::allocator<void> > MoveJointsResponse;

typedef boost::shared_ptr< ::nao_control_tutorial_2::MoveJointsResponse > MoveJointsResponsePtr;
typedef boost::shared_ptr< ::nao_control_tutorial_2::MoveJointsResponse const> MoveJointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_control_tutorial_2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "918e787cb9bd62a96492d36d89fef46a";
  }

  static const char* value(const ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x918e787cb9bd62a9ULL;
  static const uint64_t static_value2 = 0x6492d36d89fef46aULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_control_tutorial_2/MoveJointsResponse";
  }

  static const char* value(const ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32 x_pos\n\
float32 y_pos\n\
float32 z_pos\n\
float32 x_rot\n\
float32 y_rot\n\
float32 z_rot\n\
\n\
";
  }

  static const char* value(const ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_pos);
      stream.next(m.y_pos);
      stream.next(m.z_pos);
      stream.next(m.x_rot);
      stream.next(m.y_rot);
      stream.next(m.z_rot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveJointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_control_tutorial_2::MoveJointsResponse_<ContainerAllocator>& v)
  {
    s << indent << "x_pos: ";
    Printer<float>::stream(s, indent + "  ", v.x_pos);
    s << indent << "y_pos: ";
    Printer<float>::stream(s, indent + "  ", v.y_pos);
    s << indent << "z_pos: ";
    Printer<float>::stream(s, indent + "  ", v.z_pos);
    s << indent << "x_rot: ";
    Printer<float>::stream(s, indent + "  ", v.x_rot);
    s << indent << "y_rot: ";
    Printer<float>::stream(s, indent + "  ", v.y_rot);
    s << indent << "z_rot: ";
    Printer<float>::stream(s, indent + "  ", v.z_rot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_CONTROL_TUTORIAL_2_MESSAGE_MOVEJOINTSRESPONSE_H
