// Generated by gencpp from file nao_control_tutorial_1/InterpolateJoints.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_TUTORIAL_1_MESSAGE_INTERPOLATEJOINTS_H
#define NAO_CONTROL_TUTORIAL_1_MESSAGE_INTERPOLATEJOINTS_H

#include <ros/service_traits.h>


#include <nao_control_tutorial_1/InterpolateJointsRequest.h>
#include <nao_control_tutorial_1/InterpolateJointsResponse.h>


namespace nao_control_tutorial_1
{

struct InterpolateJoints
{

typedef InterpolateJointsRequest Request;
typedef InterpolateJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InterpolateJoints
} // namespace nao_control_tutorial_1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_control_tutorial_1::InterpolateJoints > {
  static const char* value()
  {
    return "d23b0af1b474d5848e69b3a31bdacede";
  }

  static const char* value(const ::nao_control_tutorial_1::InterpolateJoints&) { return value(); }
};

template<>
struct DataType< ::nao_control_tutorial_1::InterpolateJoints > {
  static const char* value()
  {
    return "nao_control_tutorial_1/InterpolateJoints";
  }

  static const char* value(const ::nao_control_tutorial_1::InterpolateJoints&) { return value(); }
};


// service_traits::MD5Sum< ::nao_control_tutorial_1::InterpolateJointsRequest> should match 
// service_traits::MD5Sum< ::nao_control_tutorial_1::InterpolateJoints > 
template<>
struct MD5Sum< ::nao_control_tutorial_1::InterpolateJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control_tutorial_1::InterpolateJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::InterpolateJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control_tutorial_1::InterpolateJointsRequest> should match 
// service_traits::DataType< ::nao_control_tutorial_1::InterpolateJoints > 
template<>
struct DataType< ::nao_control_tutorial_1::InterpolateJointsRequest>
{
  static const char* value()
  {
    return DataType< ::nao_control_tutorial_1::InterpolateJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::InterpolateJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_control_tutorial_1::InterpolateJointsResponse> should match 
// service_traits::MD5Sum< ::nao_control_tutorial_1::InterpolateJoints > 
template<>
struct MD5Sum< ::nao_control_tutorial_1::InterpolateJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control_tutorial_1::InterpolateJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::InterpolateJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control_tutorial_1::InterpolateJointsResponse> should match 
// service_traits::DataType< ::nao_control_tutorial_1::InterpolateJoints > 
template<>
struct DataType< ::nao_control_tutorial_1::InterpolateJointsResponse>
{
  static const char* value()
  {
    return DataType< ::nao_control_tutorial_1::InterpolateJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::InterpolateJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_CONTROL_TUTORIAL_1_MESSAGE_INTERPOLATEJOINTS_H
