// Generated by gencpp from file nao_control_tutorial_1/InterpolateJointsResponse.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_TUTORIAL_1_MESSAGE_INTERPOLATEJOINTSRESPONSE_H
#define NAO_CONTROL_TUTORIAL_1_MESSAGE_INTERPOLATEJOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_control_tutorial_1
{
template <class ContainerAllocator>
struct InterpolateJointsResponse_
{
  typedef InterpolateJointsResponse_<ContainerAllocator> Type;

  InterpolateJointsResponse_()
    : status(false)  {
    }
  InterpolateJointsResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InterpolateJointsResponse_

typedef ::nao_control_tutorial_1::InterpolateJointsResponse_<std::allocator<void> > InterpolateJointsResponse;

typedef boost::shared_ptr< ::nao_control_tutorial_1::InterpolateJointsResponse > InterpolateJointsResponsePtr;
typedef boost::shared_ptr< ::nao_control_tutorial_1::InterpolateJointsResponse const> InterpolateJointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_control_tutorial_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_control_tutorial_1/InterpolateJointsResponse";
  }

  static const char* value(const ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
bool status\n\
";
  }

  static const char* value(const ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterpolateJointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_control_tutorial_1::InterpolateJointsResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_CONTROL_TUTORIAL_1_MESSAGE_INTERPOLATEJOINTSRESPONSE_H
