// Generated by gencpp from file nao_control_tutorial_1/jointAngle.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_TUTORIAL_1_MESSAGE_JOINTANGLE_H
#define NAO_CONTROL_TUTORIAL_1_MESSAGE_JOINTANGLE_H

#include <ros/service_traits.h>


#include <nao_control_tutorial_1/jointAngleRequest.h>
#include <nao_control_tutorial_1/jointAngleResponse.h>


namespace nao_control_tutorial_1
{

struct jointAngle
{

typedef jointAngleRequest Request;
typedef jointAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct jointAngle
} // namespace nao_control_tutorial_1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_control_tutorial_1::jointAngle > {
  static const char* value()
  {
    return "9f94ee84ff234477d8bfe4add39a302f";
  }

  static const char* value(const ::nao_control_tutorial_1::jointAngle&) { return value(); }
};

template<>
struct DataType< ::nao_control_tutorial_1::jointAngle > {
  static const char* value()
  {
    return "nao_control_tutorial_1/jointAngle";
  }

  static const char* value(const ::nao_control_tutorial_1::jointAngle&) { return value(); }
};


// service_traits::MD5Sum< ::nao_control_tutorial_1::jointAngleRequest> should match 
// service_traits::MD5Sum< ::nao_control_tutorial_1::jointAngle > 
template<>
struct MD5Sum< ::nao_control_tutorial_1::jointAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control_tutorial_1::jointAngle >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::jointAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control_tutorial_1::jointAngleRequest> should match 
// service_traits::DataType< ::nao_control_tutorial_1::jointAngle > 
template<>
struct DataType< ::nao_control_tutorial_1::jointAngleRequest>
{
  static const char* value()
  {
    return DataType< ::nao_control_tutorial_1::jointAngle >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::jointAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_control_tutorial_1::jointAngleResponse> should match 
// service_traits::MD5Sum< ::nao_control_tutorial_1::jointAngle > 
template<>
struct MD5Sum< ::nao_control_tutorial_1::jointAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control_tutorial_1::jointAngle >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::jointAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control_tutorial_1::jointAngleResponse> should match 
// service_traits::DataType< ::nao_control_tutorial_1::jointAngle > 
template<>
struct DataType< ::nao_control_tutorial_1::jointAngleResponse>
{
  static const char* value()
  {
    return DataType< ::nao_control_tutorial_1::jointAngle >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::jointAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_CONTROL_TUTORIAL_1_MESSAGE_JOINTANGLE_H
