// Generated by gencpp from file nao_control_tutorial_1/jointAngleResponse.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_TUTORIAL_1_MESSAGE_JOINTANGLERESPONSE_H
#define NAO_CONTROL_TUTORIAL_1_MESSAGE_JOINTANGLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_control_tutorial_1
{
template <class ContainerAllocator>
struct jointAngleResponse_
{
  typedef jointAngleResponse_<ContainerAllocator> Type;

  jointAngleResponse_()
    : angle(0.0)  {
    }
  jointAngleResponse_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct jointAngleResponse_

typedef ::nao_control_tutorial_1::jointAngleResponse_<std::allocator<void> > jointAngleResponse;

typedef boost::shared_ptr< ::nao_control_tutorial_1::jointAngleResponse > jointAngleResponsePtr;
typedef boost::shared_ptr< ::nao_control_tutorial_1::jointAngleResponse const> jointAngleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_control_tutorial_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d11dcdbe5a6f73dULL;
  static const uint64_t static_value2 = 0xd324353dc52315abULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_control_tutorial_1/jointAngleResponse";
  }

  static const char* value(const ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n\
\n\
";
  }

  static const char* value(const ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jointAngleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_control_tutorial_1::jointAngleResponse_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_CONTROL_TUTORIAL_1_MESSAGE_JOINTANGLERESPONSE_H
