// Generated by gencpp from file nao_control_tutorial_1/MoveJoints.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_TUTORIAL_1_MESSAGE_MOVEJOINTS_H
#define NAO_CONTROL_TUTORIAL_1_MESSAGE_MOVEJOINTS_H

#include <ros/service_traits.h>


#include <nao_control_tutorial_1/MoveJointsRequest.h>
#include <nao_control_tutorial_1/MoveJointsResponse.h>


namespace nao_control_tutorial_1
{

struct MoveJoints
{

typedef MoveJointsRequest Request;
typedef MoveJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveJoints
} // namespace nao_control_tutorial_1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_control_tutorial_1::MoveJoints > {
  static const char* value()
  {
    return "4e50cd843f7a75f4fe9793a5badaf911";
  }

  static const char* value(const ::nao_control_tutorial_1::MoveJoints&) { return value(); }
};

template<>
struct DataType< ::nao_control_tutorial_1::MoveJoints > {
  static const char* value()
  {
    return "nao_control_tutorial_1/MoveJoints";
  }

  static const char* value(const ::nao_control_tutorial_1::MoveJoints&) { return value(); }
};


// service_traits::MD5Sum< ::nao_control_tutorial_1::MoveJointsRequest> should match 
// service_traits::MD5Sum< ::nao_control_tutorial_1::MoveJoints > 
template<>
struct MD5Sum< ::nao_control_tutorial_1::MoveJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control_tutorial_1::MoveJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::MoveJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control_tutorial_1::MoveJointsRequest> should match 
// service_traits::DataType< ::nao_control_tutorial_1::MoveJoints > 
template<>
struct DataType< ::nao_control_tutorial_1::MoveJointsRequest>
{
  static const char* value()
  {
    return DataType< ::nao_control_tutorial_1::MoveJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::MoveJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_control_tutorial_1::MoveJointsResponse> should match 
// service_traits::MD5Sum< ::nao_control_tutorial_1::MoveJoints > 
template<>
struct MD5Sum< ::nao_control_tutorial_1::MoveJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control_tutorial_1::MoveJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::MoveJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control_tutorial_1::MoveJointsResponse> should match 
// service_traits::DataType< ::nao_control_tutorial_1::MoveJoints > 
template<>
struct DataType< ::nao_control_tutorial_1::MoveJointsResponse>
{
  static const char* value()
  {
    return DataType< ::nao_control_tutorial_1::MoveJoints >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::MoveJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_CONTROL_TUTORIAL_1_MESSAGE_MOVEJOINTS_H
