// Generated by gencpp from file nao_control_tutorial_1/timedInterpolation.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_TUTORIAL_1_MESSAGE_TIMEDINTERPOLATION_H
#define NAO_CONTROL_TUTORIAL_1_MESSAGE_TIMEDINTERPOLATION_H

#include <ros/service_traits.h>


#include <nao_control_tutorial_1/timedInterpolationRequest.h>
#include <nao_control_tutorial_1/timedInterpolationResponse.h>


namespace nao_control_tutorial_1
{

struct timedInterpolation
{

typedef timedInterpolationRequest Request;
typedef timedInterpolationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct timedInterpolation
} // namespace nao_control_tutorial_1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_control_tutorial_1::timedInterpolation > {
  static const char* value()
  {
    return "062c7554adac44a703a2883e86bbb559";
  }

  static const char* value(const ::nao_control_tutorial_1::timedInterpolation&) { return value(); }
};

template<>
struct DataType< ::nao_control_tutorial_1::timedInterpolation > {
  static const char* value()
  {
    return "nao_control_tutorial_1/timedInterpolation";
  }

  static const char* value(const ::nao_control_tutorial_1::timedInterpolation&) { return value(); }
};


// service_traits::MD5Sum< ::nao_control_tutorial_1::timedInterpolationRequest> should match 
// service_traits::MD5Sum< ::nao_control_tutorial_1::timedInterpolation > 
template<>
struct MD5Sum< ::nao_control_tutorial_1::timedInterpolationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control_tutorial_1::timedInterpolation >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::timedInterpolationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control_tutorial_1::timedInterpolationRequest> should match 
// service_traits::DataType< ::nao_control_tutorial_1::timedInterpolation > 
template<>
struct DataType< ::nao_control_tutorial_1::timedInterpolationRequest>
{
  static const char* value()
  {
    return DataType< ::nao_control_tutorial_1::timedInterpolation >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::timedInterpolationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_control_tutorial_1::timedInterpolationResponse> should match 
// service_traits::MD5Sum< ::nao_control_tutorial_1::timedInterpolation > 
template<>
struct MD5Sum< ::nao_control_tutorial_1::timedInterpolationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control_tutorial_1::timedInterpolation >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::timedInterpolationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control_tutorial_1::timedInterpolationResponse> should match 
// service_traits::DataType< ::nao_control_tutorial_1::timedInterpolation > 
template<>
struct DataType< ::nao_control_tutorial_1::timedInterpolationResponse>
{
  static const char* value()
  {
    return DataType< ::nao_control_tutorial_1::timedInterpolation >::value();
  }
  static const char* value(const ::nao_control_tutorial_1::timedInterpolationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_CONTROL_TUTORIAL_1_MESSAGE_TIMEDINTERPOLATION_H
