(cl:defpackage nao_control_tutorial_1-srv
  (:use )
  (:export
   "JOINTANGLE"
   "<JOINTANGLE-REQUEST>"
   "JOINTANGLE-REQUEST"
   "<JOINTANGLE-RESPONSE>"
   "JOINTANGLE-RESPONSE"
   "TIMEDINTERPOLATION"
   "<TIMEDINTERPOLATION-REQUEST>"
   "TIMEDINTERPOLATION-REQUEST"
   "<TIMEDINTERPOLATION-RESPONSE>"
   "TIMEDINTERPOLATION-RESPONSE"
  ))

