// Generated by gencpp from file tutorial7/blinkFeedback.msg
// DO NOT EDIT!


#ifndef TUTORIAL7_MESSAGE_BLINKFEEDBACK_H
#define TUTORIAL7_MESSAGE_BLINKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/ColorRGBA.h>

namespace tutorial7
{
template <class ContainerAllocator>
struct blinkFeedback_
{
  typedef blinkFeedback_<ContainerAllocator> Type;

  blinkFeedback_()
    : last_color()  {
    }
  blinkFeedback_(const ContainerAllocator& _alloc)
    : last_color(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _last_color_type;
  _last_color_type last_color;





  typedef boost::shared_ptr< ::tutorial7::blinkFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial7::blinkFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct blinkFeedback_

typedef ::tutorial7::blinkFeedback_<std::allocator<void> > blinkFeedback;

typedef boost::shared_ptr< ::tutorial7::blinkFeedback > blinkFeedbackPtr;
typedef boost::shared_ptr< ::tutorial7::blinkFeedback const> blinkFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial7::blinkFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial7::blinkFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tutorial7

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'tutorial7': ['/home/hrsb/MSNE_HRS/catkin_ws/devel/share/tutorial7/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tutorial7::blinkFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial7::blinkFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial7::blinkFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial7::blinkFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial7::blinkFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial7::blinkFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial7::blinkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f1f94fb3eb06412264f6e0c5e72cfab";
  }

  static const char* value(const ::tutorial7::blinkFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f1f94fb3eb06412ULL;
  static const uint64_t static_value2 = 0x264f6e0c5e72cfabULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial7::blinkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial7/blinkFeedback";
  }

  static const char* value(const ::tutorial7::blinkFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial7::blinkFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
# Feedback \n\
std_msgs/ColorRGBA last_color\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/ColorRGBA\n\
float32 r\n\
float32 g\n\
float32 b\n\
float32 a\n\
";
  }

  static const char* value(const ::tutorial7::blinkFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial7::blinkFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.last_color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct blinkFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial7::blinkFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial7::blinkFeedback_<ContainerAllocator>& v)
  {
    s << indent << "last_color: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.last_color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL7_MESSAGE_BLINKFEEDBACK_H
