// Generated by gencpp from file tutorial7/blinkResult.msg
// DO NOT EDIT!


#ifndef TUTORIAL7_MESSAGE_BLINKRESULT_H
#define TUTORIAL7_MESSAGE_BLINKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial7
{
template <class ContainerAllocator>
struct blinkResult_
{
  typedef blinkResult_<ContainerAllocator> Type;

  blinkResult_()
    : still_blinking(false)  {
    }
  blinkResult_(const ContainerAllocator& _alloc)
    : still_blinking(false)  {
  (void)_alloc;
    }



   typedef uint8_t _still_blinking_type;
  _still_blinking_type still_blinking;





  typedef boost::shared_ptr< ::tutorial7::blinkResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial7::blinkResult_<ContainerAllocator> const> ConstPtr;

}; // struct blinkResult_

typedef ::tutorial7::blinkResult_<std::allocator<void> > blinkResult;

typedef boost::shared_ptr< ::tutorial7::blinkResult > blinkResultPtr;
typedef boost::shared_ptr< ::tutorial7::blinkResult const> blinkResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial7::blinkResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial7::blinkResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tutorial7

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'tutorial7': ['/home/hrsb/MSNE_HRS/catkin_ws/devel/share/tutorial7/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tutorial7::blinkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial7::blinkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial7::blinkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial7::blinkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial7::blinkResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial7::blinkResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial7::blinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53e041b81450f9247036f13b3c0bf822";
  }

  static const char* value(const ::tutorial7::blinkResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53e041b81450f924ULL;
  static const uint64_t static_value2 = 0x7036f13b3c0bf822ULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial7::blinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial7/blinkResult";
  }

  static const char* value(const ::tutorial7::blinkResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial7::blinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result \n\
bool still_blinking\n\
\n\
";
  }

  static const char* value(const ::tutorial7::blinkResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial7::blinkResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.still_blinking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct blinkResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial7::blinkResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial7::blinkResult_<ContainerAllocator>& v)
  {
    s << indent << "still_blinking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.still_blinking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL7_MESSAGE_BLINKRESULT_H
