(cl:defpackage nao_control_tutorial_1-srv
  (:use )
  (:export
   "INTERPOLATEJOINTS"
   "<INTERPOLATEJOINTS-REQUEST>"
   "INTERPOLATEJOINTS-REQUEST"
   "<INTERPOLATEJOINTS-RESPONSE>"
   "INTERPOLATEJOINTS-RESPONSE"
   "MOVEJOINTS"
   "<MOVEJOINTS-REQUEST>"
   "MOVEJOINTS-REQUEST"
   "<MOVEJOINTS-RESPONSE>"
   "MOVEJOINTS-RESPONSE"
  ))

