// Auto-generated. Do not edit!

// (in-package tutorial7.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class blinkResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.still_blinking = null;
    }
    else {
      if (initObj.hasOwnProperty('still_blinking')) {
        this.still_blinking = initObj.still_blinking
      }
      else {
        this.still_blinking = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type blinkResult
    // Serialize message field [still_blinking]
    bufferOffset = _serializer.bool(obj.still_blinking, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type blinkResult
    let len;
    let data = new blinkResult(null);
    // Deserialize message field [still_blinking]
    data.still_blinking = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'tutorial7/blinkResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '53e041b81450f9247036f13b3c0bf822';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result 
    bool still_blinking
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new blinkResult(null);
    if (msg.still_blinking !== undefined) {
      resolved.still_blinking = msg.still_blinking;
    }
    else {
      resolved.still_blinking = false
    }

    return resolved;
    }
};

module.exports = blinkResult;
